name: NuGet Package Publisher

on:
  push:
    tags: ['*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Restore dependencies
      run: dotnet restore src/Transil/Transil.csproj

    - name: Build Transil
      run: dotnet build src/Transil/Transil.csproj -c Release --no-restore

    - name: Pack and Publish Transil
      run: |
        TAG_NAME=${{ github.ref_name }}
        dotnet pack src/Transil/Transil.csproj -c Release -p:PackageVersion=$TAG_NAME --output nupkg
        dotnet nuget push "nupkg/Transil.*.nupkg" --source github
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}