name: NuGet Package Publisher

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore projects/Transil/Transil.csproj

    - name: Build project
      run: dotnet build projects/Transil/Transil.csproj -c Release --no-restore

    - name: Create NuGet package
      id: pack
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}

        dotnet pack projects/Transil/Transil.csproj \
          -c Release \
          --no-build \
          -p:PackageVersion=$VERSION \
          -p:ContinuousIntegrationBuild=true \
          --output nupkg

        echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_OUTPUT

        echo "Generated packages:"
        ls -lh nupkg/

    - name: Publish to GitHub Packages
      run: |
        dotnet nuget push "nupkg/LF2.Transil.${{ steps.pack.outputs.PACKAGE_VERSION }}.nupkg" \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
